# Plant chance as a percentage. Must be a positive integer 0-100. Seeds excluded here will not be planted.
Plants:
  ACACIA_SAPLING: 33
  AZALEA: 33
  FLOWERING_AZALEA: 33
  SPRUCE_SAPLING: 33
  BAMBOO: 33
  CHERRY_SAPLING: 33
  BIRCH_SAPLING: 33
  JUNGLE_SAPLING: 33
  DARK_OAK_SAPLING: 33
  OAK_SAPLING: 33
  MANGROVE_PROPAGULE: 33
  WHEAT_SEEDS: 50
  POTATO: 50
  BEETROOT_SEEDS: 50
  CARROT: 50
  MELON_SEEDS: 50
  PUMPKIN_SEEDS: 50
  TORCHFLOWER_SEEDS: 50
  PITCHER_POD: 50
  SWEET_BERRIES: 50
  SUGAR_CANE: 50
  CACTUS: 50
  RED_MUSHROOM: 50
  BROWN_MUSHROOM: 50
  NETHER_WART: 50